server {
    listen 80;
    listen [::]:80;
    server_name print.1to.top;
    client_max_body_size 100m;

    root __FRONTEND_DEPLOY_DIR__;
    index index.html;

    location /.well-known/acme-challenge/ {
        root __FRONTEND_DEPLOY_DIR__;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name print.1to.top;
    client_max_body_size 100m;

    root __FRONTEND_DEPLOY_DIR__;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/print.1to.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/print.1to.top/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    location /.well-known/acme-challenge/ {
        root __FRONTEND_DEPLOY_DIR__;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
